### PR TITLE
Review week 14

### PR DESCRIPTION
**Pull request by larasodjati**
Add new components and styling some app's components.

### CODE REVIEW

**Review by achasek — APPROVED** [review]
It looks like all of the changes were primarily CSS. The only other change that I see is a change in one of the routes. All looks good, though. I do have 1 question with your code in TodoOverview.js starting on line 68. Is there a reason that, in the forEach() loop, that you opted to use the .push() method there instead of a more React-friendly method like .concat()?

**Comment by larasodjati** [comment]
Hi @achasek, thank you for the feedback! To be honest with you, I use .push() within the forEach() loop because those are the methods I am already quite familiar with. I just knew we could use a React-friendly method like .concat(), would it look like this if we use the concat method?

`todoList.forEach((todo) => {
const category = todo.category;
  if (!todo.completed) {
    if (!pendingCategories[category]) {
      pendingCategories[category] = [todo];
    } else {
      pendingCategories[category] = pendingCategories[category].concat(todo);
    }
  }
});`

**Comment by achasek** [comment]
So when using React, when dealing with state or data in your application and manipulating/changing that, you want to use methods that create copies of the state or data and never want to manipulate the original state directly. 

Look at the difference between a .forEach() loop and .map() in JavaScript. A forEach() loop is in-place, meaning that it modifies the array that it is being used on, whereas map() is out-of-place, meaning that it creates a copy of the array that it is being used on. If you modify an array with map(), you will have 2 copies: The original unmodified array, and then the modified array. You want to use out-of-place methods that create copies when using React. 

The same can be said about .push() versus .concat(). 
.push() is in-place, which pushes a new element to the ORIGINAL ARRAY, whereas 
.concat() is out-of-place, which creates a NEW ARRAY, a copy of the original, that combines the old array with the new element that you are trying to add to it.

So if you wanted to use .concat() in your code, it would look something like this:
(And me, only being able to see a small part of your code, the exact syntax that would work in your application may differ a little from what I suggest here)

pendingCategories.concat(todo)

This is assuming that pendingCategories is an array of data. I may be wrong, though. So here is the generic formula for .concat() and this can be found on MDN web documentation as well.

someArray.concat(thingToAddToSomeArray)

However, if you are going to use .concat(), which I would suggest that you do, but if you are, you may want to change that entire code block inside of the forEach() loop, because you will run into bugs if you use an in-palce method, like forEach(), with an out-of-palce method like .concat(). If you are using an out-of-place method in 1 area, you will want to use out-of-place methods for the rest of that block or function. 

So you will almost certainly need to replace the forEach() block with an out-of-place method like .map() for this to work. So something like:

todoList.map((todo) => {
	<the rest of your code>
	arrayThatYouAreTryingToAddTodoTo.concat(newTodo)
} )

**Comment by larasodjati** [comment]
Hi @achasek, thank you for the explanation. Initially, I thought I could achieve my goal (in this case, calculating the pending categories) by modifying the existing array instead of creating a new one, which is why I used the familiar methods .forEach() and .push(). However, after reading about .concat(), I made some edits, as you can see in my latest commit. I also printed the log to my console, and it appears to be returning the correct results. Please let me know if it's now correct?

**Pull request merged**
